theme: jekyll-theme-minimal
title: Homepage
description: Bookmark this to keep an eye on my project updates!

# Additional configurations
url: "https://ASAD-BE18.github.io/ASAD-BE18"
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: your_twitter_username
github_username: ASAD-BE18

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO
seo:
  title: "Homepage"
  description: "Bookmark this to keep an eye on my project updates!"
  author: "ASAD-BE18"

# Exclude specific files or directories from the build process
exclude:
  - README.md
  - LICENSE

# Include additional files or directories in the build process
include:
  - _pages
  - _posts

# Enable collections
collections:
  my_collection:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "ASAD-BE18"
